"""init migration

Revision ID: e4cfdd936f72
Revises: b17864c44e6f
Create Date: 2023-06-07 17:28:43.976748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4cfdd936f72'
down_revision = 'b17864c44e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.drop_constraint('divisions_job_id_fkey', type_='foreignkey')
        batch_op.drop_column('job_id')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('employees_job_id_fkey', type_='foreignkey')
        batch_op.drop_column('job_id')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('division_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'positions', ['position_id'], ['id'])
        batch_op.create_foreign_key(None, 'divisions', ['division_id'], ['id'])
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'])

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_constraint('positions_job_id_fkey', type_='foreignkey')
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('positions_job_id_fkey', 'job', ['job_id'], ['id'])

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('division_id')
        batch_op.drop_column('position_id')
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('employees_job_id_fkey', 'job', ['job_id'], ['id'])

    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('divisions_job_id_fkey', 'job', ['job_id'], ['id'])

    # ### end Alembic commands ###
